# Generated by Django 2.1.4 on 2018-12-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('sname', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('sex', models.CharField(max_length=1)),
                ('birth', models.BigIntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('joined', models.BigIntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BigIntegerField()),
                ('finish', models.BigIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Account')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSympathy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.BigIntegerField()),
                ('likee', models.BigIntegerField()),
                ('ts', models.BigIntegerField()),
            ],
        ),
    ]
