# Generated by Django 2.1.4 on 2018-12-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_interest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interest',
            new_name='AccountInterest',
        ),
        migrations.RenameModel(
            old_name='Subscription',
            new_name='AccountSubscription',
        ),
        migrations.RenameModel(
            old_name='Sympathy',
            new_name='AccountSympathy',
        ),
    ]
