# Generated by Django 2.1.4 on 2018-12-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20181217_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsympathy',
            name='likee',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='accountsympathy',
            name='liker',
            field=models.BigIntegerField(),
        ),
    ]
